server:
  port: 9003
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
