server:
  port: 9000 #端口号
spring:
  application:
    name: "eureka-server" #服务名
eureka:
  client:
    register-with-eureka: false #是否注册到Eureka（eureka本身是不需要再注册到自己的）
    fetch-registry: false #是否从Eureka获取注册信息
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/ # eureka服务器的地址（注意：地址最后面的 /eureka/ 这个是固定值）
  instance:
    lease-expiration-duration-in-seconds: 90 #服务失效时间，Eureka多长时间没收到服务的renew操作，就剔除该服务，默认90秒
  server:
    eviction-interval-timer-in-ms: 2000 #eureka server清理无效节点的时间间隔，默认0毫秒
    enable-self-preservation: true # 自我保护模式（缺省为打开）
