server:
  port: 9002
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost/spring-cloud-oauth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/